# Generated by Django 2.0.6 on 2019-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=100)),
                ('Data_criacao', models.DateField()),
                ('Data_vencimento', models.DateField()),
                ('Valor', models.FloatField()),
                ('Tipo_despesa', models.CharField(choices=[('AL', 'Alimentação'), ('MO', 'Moradia'), ('CO', 'Combustível')], max_length=2)),
                ('Forma_pagamento', models.CharField(choices=[('ES', 'Especie'), ('BO', 'Boleto'), ('CA', 'Cartão')], max_length=2)),
                ('Quitado', models.BooleanField()),
            ],
        ),
    ]
